<form class="log-in-form" method="POST" action="/myaccount/changeData">
 
    <label>Username
    <input type="text" id="username" name="username" value="<?php 
    echo $row->username;?>">
    </label>

    <label>Email
    <input type="email" id="email" name="email" value="<?php 
    echo $row->email;?>">
    </label>

    <label>Adress
    <input type="text" id="adress" name="adress" value="<?php 
    echo $row->adress;
    ?>">
    </label>

    <label>New Pasword
    <input type="password" id="password" name="password">
    </label>

    <label>Repeat password
    <input type="password" id="repeat" name="repeat">
    </label>

    <?php if(isset($message)) echo $message; ?><br>

    <input type="submit" class="button" value="Change Data"></input>
   <a href="#" class="button">Remove Account</a>
  
    <input type="hidden" name="id" value="<?php echo $row->id ?>">

</form>








    
  