<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title"><?php echo APP::config('appname'); ?></div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out" >
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu > 
            <li class="menu-text show-for-large">
            <?php echo APP::config('appname'); ?>
            </li>
            <li><a href="/index"> Home </a></li>           
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">       
            <li><a href="/index/loginPage"> Log in </a></li>
            <li> <a href="/index/registrationPage"> Registration </a></li>
        </ul>
    </div>
</div>
