<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title"><?php echo APP::config('appname'); ?></div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out" >
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu > 
            <li class="menu-text show-for-large">
                <?php echo APP::config('appname'); ?>
            </li>
            <li><a href="/index"> Home </a></li>
                <?php if(isset($_SESSION['user'])):?>
            <li><a href="/management/funkcija"> Management </a></li>
            <li><a href="/myaccount/funkcija"> My Account </a>
                <?php endif; ?>        
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
        <?php if(isset($_SESSION['user'])):?>   
            <li><a href="/index/logout"><?php echo $_SESSION['user']->username ?> Log Out </a></li>
        <?php else: ?>     
            <li><a href="/index/loginPage"> Log In </a></li>
            <li> <a href="/index/registrationPage"> Registration </a></li>
        <?php endif; ?> 
        </ul>
    </div>
</div>
