<form class="log-in-form" method="POST" action="/index/autorization">  
    <label> Email
    <input type ="email" id ="email" name ="email" 
    value ="<?php if(isset($_COOKIE["email"])) { echo $_COOKIE["email"]; } ?>">
    </label>

    <label > Password
    <input type = "password" id = "password" name = "password"
	value="<?php if(isset($_COOKIE["password"])) { echo $_COOKIE["password"]; } ?>">
    </label>

    <input type="checkbox" id="remember" name="remember"  
    <?php if(isset($_COOKIE["email"])) { ?> checked <?php } ?> />
	<label for="remember-me">Remember me</label>

    <?php echo '<br>' . $message; ?>
    <input type = "submit" class = "button expanded" name = "login" value = "Log In" ></input>
  
</form>

<a href = "/index/registrationPage" class = "button expanded" > Sign Up </a>
